# Kubernetes deployment manifest for Weather Service
# Updated for Oracle Cloud Infrastructure (OCI) Kubernetes Engine deployment
# Last updated: 2025-05-14 - Optimized for OCI Free Tier
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  labels:
    app: weatherservice
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherservice
      component: api
  template:
    metadata:
      labels:
        app: weatherservice
        component: api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api
        image: ghcr.io/mcannall/weatherservice:${GITHUB_SHA}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: OpenWeatherMap__ApiKey
          valueFrom:
            secretKeyRef:
              name: weatherservice-secrets
              key: OPENWEATHERMAP_API_KEY
        - name: OpenWeatherMap__BaseUrl
          value: "https://api.openweathermap.org/data/2.5"
---
# Route planner configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-planner
  labels:
    app: weatherservice
    component: route-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherservice
      component: route-planner
  template:
    metadata:
      labels:
        app: weatherservice
        component: route-planner
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: route-planner
        image: ghcr.io/mcannall/weatherservice/route-weather-planner:${GITHUB_SHA}
        imagePullPolicy: IfNotPresent
        command:
        - gunicorn
        args:
        - --workers=2
        - --bind=0.0.0.0:5000
        - --access-logfile=-
        - --error-logfile=-
        - --log-level=info
        - --timeout=120
        - --preload
        - wsgi:app
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        env:
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: weatherservice-secrets
              key: GOOGLE_MAPS_API_KEY
        - name: API_URL
          value: http://weather-api-service 