apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  labels:
    app: weatherservice
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherservice
      component: api
  template:
    metadata:
      labels:
        app: weatherservice
        component: api
    spec:
      containers:
      - name: api
        image: ghcr.io/mcannall/weatherservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: OpenWeatherMap__ApiKey
          valueFrom:
            secretKeyRef:
              name: weatherservice-secrets
              key: OPENWEATHERMAP_API_KEY
        - name: OpenWeatherMap__BaseUrl
          value: "https://api.openweathermap.org/data/2.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-planner
  labels:
    app: weatherservice
    component: route-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherservice
      component: route-planner
  template:
    metadata:
      labels:
        app: weatherservice
        component: route-planner
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: route-planner
        image: ghcr.io/mcannall/weatherservice/route-weather-planner:latest
        imagePullPolicy: Always
        command:
        - gunicorn
        args:
        - --workers=4
        - --bind=0.0.0.0:5000
        - --access-logfile=-
        - --error-logfile=-
        - --log-level=info
        - --preload
        - wsgi:app
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: weatherservice-secrets
              key: GOOGLE_MAPS_API_KEY
        - name: API_URL
          value: http://weather-api-service
      imagePullSecrets:
      - name: ghcr-secret 