apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: weatherservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: weatherservice 