apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  labels:
    app: weatherservice
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: weatherservice
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: route-planner-service
  labels:
    app: weatherservice
    component: route-planner
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: weatherservice
    component: route-planner 