apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-weather-planner
  labels:
    app: route-weather-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-weather-planner
  template:
    metadata:
      labels:
        app: route-weather-planner
    spec:
      containers:
      - name: route-weather-planner
        image: ghcr.io/mcannall/weatherservice/route-weather-planner:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: weatherservice-secrets
              key: GOOGLE_MAPS_API_KEY
        - name: API_URL
          value: "http://api:80"  # Points to the API service
---
apiVersion: v1
kind: Service
metadata:
  name: route-weather-planner
spec:
  selector:
    app: route-weather-planner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP 