apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/${{ github.repository }}/weatherservice:latest  # Use GitHub Container Registry
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # You can specify a port or let Kubernetes assign one
  selector:
    app: api
    
