name: Test Oracle Cloud Connectivity

on:
  workflow_dispatch:
    inputs:
      run-oracle-list-cmd:
        description: 'Run Oracle list command'
        type: boolean
        default: true
      run-oke-test:
        description: 'Test OKE Kubernetes connection'
        type: boolean
        default: true
      region:
        description: 'Oracle Cloud Region (default: us-chicago-1)'
        required: false
        type: string
        default: 'us-chicago-1'
      cluster_id:
        description: 'OKE Cluster ID (leave empty to use secret)'
        required: false
        type: string
      compartment_id:
        description: 'Compartment ID (leave empty to use tenancy)'
        required: false
        type: string

jobs:
  test-oci-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          echo "Installing OCI CLI..."
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          
          # Add OCI CLI to PATH
          echo "/home/runner/bin" >> $GITHUB_PATH
          
          # Verify installation
          echo "OCI CLI version:"
          /home/runner/bin/oci -v
          
      - name: Configure OCI CLI
        run: |
          echo "Configuring OCI CLI..."
          mkdir -p ~/.oci
          
          # Create private key file
          echo "Creating private key file..."
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          
          # Add OCI_API_KEY label to suppress warning
          echo "OCI_API_KEY" >> ~/.oci/oci_api_key.pem
          
          # Determine region to use
          REGION="${{ github.event.inputs.region }}"
          if [ -z "$REGION" ]; then
            REGION="us-chicago-1"  # Default to Chicago region
          fi
          echo "Using region: $REGION"
          
          # Create config file
          echo "Creating config file..."
          cat > ~/.oci/config << EOF
          [DEFAULT]
          user=${{ secrets.OCI_CLI_USER }}
          fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_CLI_TENANCY }}
          region=$REGION
          key_file=~/.oci/oci_api_key.pem
          EOF
          chmod 600 ~/.oci/config
          
          # Verify files exist
          echo "Verifying config files exist:"
          ls -la ~/.oci/
          
          # Print config file (redacting sensitive info)
          echo "Config file contents (redacted):"
          cat ~/.oci/config | sed 's/user=.*/user=<REDACTED>/g' | sed 's/fingerprint=.*/fingerprint=<REDACTED>/g' | sed 's/tenancy=.*/tenancy=<REDACTED>/g'
          
          # Verify file permissions
          /home/runner/bin/oci setup repair-file-permissions --file ~/.oci/config
          /home/runner/bin/oci setup repair-file-permissions --file ~/.oci/oci_api_key.pem
          
          # Display OCI region
          echo "OCI Region set to: $REGION"
          
          # Test DNS resolution for region endpoint
          echo "Testing DNS resolution for region endpoint..."
          host identity.$REGION.oraclecloud.com || echo "DNS resolution failed - check region name format"
          
          # Try common regions for DNS testing to validate connectivity
          echo "Testing DNS resolution for known Oracle Cloud regions..."
          echo "US East (Ashburn):"
          host identity.us-ashburn-1.oraclecloud.com || echo "Failed to resolve US East region"
          echo "US West (Phoenix):"
          host identity.us-phoenix-1.oraclecloud.com || echo "Failed to resolve US West region"

      - name: Test OCI Connectivity without Specific Region
        run: |
          echo "Testing basic OCI connectivity with global endpoint..."
          
          # Suppress the label warning
          export SUPPRESS_LABEL_WARNING=True
          
          # Try connecting to a global endpoint that doesn't require region
          /home/runner/bin/oci --debug iam region list
          
      - name: Test OCI Connectivity with Debug Mode
        run: |
          echo "Testing basic OCI connectivity with debug mode..."
          # Set timeout environment variable
          export OCI_CLI_CALL_TIMEOUT=300
          # Suppress the label warning
          export SUPPRESS_LABEL_WARNING=True
          
          # Determine region to use
          REGION="${{ github.event.inputs.region }}"
          if [ -z "$REGION" ]; then
            REGION="us-chicago-1"  # Default to Chicago region
          fi
          
          # Try a simple command first
          echo "Testing region list command..."
          /home/runner/bin/oci --debug iam region list
          
          # Try availability domain command
          echo "Testing availability domain listing..."
          /home/runner/bin/oci --debug iam availability-domain list --region $REGION
          echo "✓ Successfully connected to OCI and listed availability domains"
      
      - name: List OCI Resources
        if: ${{ github.event.inputs.run-oracle-list-cmd == 'true' && success() }}
        run: |
          echo "Listing OCI resources..."
          # Determine region to use
          REGION="${{ github.event.inputs.region }}"
          if [ -z "$REGION" ]; then
            REGION="us-chicago-1"  # Default to Chicago region
          fi
          
          echo "Compartments:"
          /home/runner/bin/oci iam compartment list --region $REGION
          
          echo "Regions:"
          /home/runner/bin/oci iam region list
          
          echo "✓ Successfully listed OCI resources"
      
      - name: List Available OKE Clusters
        if: ${{ github.event.inputs.run-oke-test == 'true' && success() }}
        run: |
          # Determine region to use
          REGION="${{ github.event.inputs.region }}"
          if [ -z "$REGION" ]; then
            REGION="us-chicago-1"  # Default to Chicago region
          fi
          
          # Get tenancy ID to use as default compartment
          TENANCY_ID="${{ secrets.OCI_CLI_TENANCY }}"
          echo "Using tenancy as root compartment: ${TENANCY_ID:0:12}... (truncated for security)"
          
          # Use compartment ID from input or default to tenancy
          COMPARTMENT_ID="${{ github.event.inputs.compartment_id }}"
          if [ -z "$COMPARTMENT_ID" ]; then
            COMPARTMENT_ID="$TENANCY_ID"
          fi
          
          echo "Listing available OKE clusters in region $REGION, compartment $COMPARTMENT_ID..."
          /home/runner/bin/oci ce cluster list --compartment-id "$COMPARTMENT_ID" --region $REGION
          
          # Get my user details (for troubleshooting)
          echo "Getting user information..."
          /home/runner/bin/oci iam user get --user-id "${{ secrets.OCI_CLI_USER }}" --region $REGION || echo "Failed to get user info"
          
          # Check permissions
          echo "Checking compartment access and policies..."
          /home/runner/bin/oci iam policy list --compartment-id "$COMPARTMENT_ID" --region $REGION || echo "Failed to list policies"
      
      - name: Test OKE Kubernetes Connection
        if: ${{ github.event.inputs.run-oke-test == 'true' && success() }}
        run: |
          echo "Testing OKE Kubernetes connection..."
          
          # Determine region to use
          REGION="${{ github.event.inputs.region }}"
          if [ -z "$REGION" ]; then
            REGION="us-chicago-1"  # Default to Chicago region
          fi
          
          # Determine cluster ID to use
          CLUSTER_ID="${{ github.event.inputs.cluster_id }}"
          if [ -z "$CLUSTER_ID" ]; then
            CLUSTER_ID="${{ secrets.OCI_CLUSTER_ID }}"
            if [ -z "$CLUSTER_ID" ]; then
              echo "Error: No cluster ID provided in input or secrets"
              echo "Please set the OCI_CLUSTER_ID secret or provide a cluster ID in the workflow input"
              exit 1
            fi
            echo "Using cluster ID from secrets: ${CLUSTER_ID:0:8}... (truncated for security)"
          else
            echo "Using cluster ID from input: ${CLUSTER_ID:0:8}... (truncated for security)"
          fi
          
          # Get tenancy ID to use as default compartment
          TENANCY_ID="${{ secrets.OCI_CLI_TENANCY }}"
          
          # Verify that the cluster ID exists if safe to do so
          if [ -n "$CLUSTER_ID" ]; then
            echo "Verifying cluster ID..."
            /home/runner/bin/oci ce cluster get --cluster-id "$CLUSTER_ID" --region $REGION || {
              echo "Error: Cluster with ID ${CLUSTER_ID:0:8}... not found or you don't have permission to access it."
              echo "Please check the OCI_CLUSTER_ID secret or provide a valid cluster ID in the workflow input"
              echo "If you have no clusters yet, you may need to create one in your OCI account first."
              exit 1
            }
          fi
          
          echo "Cluster found! Generating kubeconfig..."
          
          # Generate kubeconfig
          mkdir -p $HOME/.kube
          /home/runner/bin/oci ce cluster create-kubeconfig \
            --cluster-id "$CLUSTER_ID" \
            --file $HOME/.kube/config \
            --region $REGION \
            --token-version 2.0.0
          
          chmod 600 $HOME/.kube/config
          
          # Verify connection
          kubectl get nodes
          echo "✓ Successfully connected to OKE Kubernetes cluster" 